const attributionAuthorFields = [
  { name: 'given', type: 'string', title: 'Given name' },
  { name: 'family', type: 'string', title: 'Family name' },
  { name: 'displayName', type: 'string', title: 'Display name' },
  { name: 'orcid', type: 'string', title: 'ORCID' },
  { name: 'affiliations', type: 'array', of: [{ type: 'string' }], title: 'Affiliations' },
]

const snapshotFields = [
  { name: 'publicationKey', type: 'string', title: 'Canonical key' },
  { name: 'pmid', type: 'string', title: 'PMID' },
  { name: 'doi', type: 'string', title: 'DOI' },
  { name: 'title', type: 'string', title: 'Title' },
  { name: 'authors', type: 'array', of: [{ type: 'string' }], title: 'Authors' },
  {
    name: 'attributionAuthors',
    type: 'array',
    title: 'Structured authors',
    of: [{ type: 'object', fields: attributionAuthorFields }],
  },
  { name: 'journal', type: 'string', title: 'Journal' },
  { name: 'publishedAt', type: 'datetime', title: 'Publication date' },
  { name: 'year', type: 'number', title: 'Year' },
  { name: 'month', type: 'string', title: 'Month' },
  { name: 'url', type: 'url', title: 'URL' },
  { name: 'source', type: 'string', title: 'Primary source' },
  { name: 'sources', type: 'array', of: [{ type: 'string' }], title: 'Sources' },
  { name: 'attributionQueryPaths', type: 'array', of: [{ type: 'string' }], title: 'Query paths' },
  { name: 'openAlexId', type: 'string', title: 'OpenAlex ID' },
  { name: 'europePmcId', type: 'string', title: 'Europe PMC ID' },
  { name: 'abstract', type: 'text', title: 'Abstract or article body' },
  { name: 'abstractContentType', type: 'string', title: 'Text type' },
  { name: 'abstractSource', type: 'string', title: 'Text source' },
  { name: 'publicationTypes', type: 'array', of: [{ type: 'string' }], title: 'Publication types' },
  { name: 'laySummary', type: 'text', title: 'Lay summary' },
  { name: 'topics', type: 'array', of: [{ type: 'string' }], title: 'Topics' },
  { name: 'studyDesign', type: 'array', of: [{ type: 'string' }], title: 'Study design' },
  { name: 'methodologicalFocus', type: 'array', of: [{ type: 'string' }], title: 'Methodological focus' },
  { name: 'exclude', type: 'boolean', title: 'Excluded from display' },
]

const publicationAttributionReview = {
  name: 'publicationAttributionReview',
  title: 'Publication Attribution Review',
  type: 'document',
  fields: [
    {
      name: 'researcher',
      title: 'Proposed researcher',
      type: 'reference',
      to: [{ type: 'researcher' }],
      validation: (Rule) => Rule.required(),
      readOnly: true,
    },
    { name: 'researcherName', title: 'Researcher name snapshot', type: 'string', readOnly: true },
    { name: 'publicationKey', title: 'Canonical publication key', type: 'string', readOnly: true },
    { name: 'doi', title: 'DOI', type: 'string', readOnly: true },
    { name: 'pmid', title: 'PMID', type: 'string', readOnly: true },
    { name: 'title', title: 'Title', type: 'string', readOnly: true },
    { name: 'authors', title: 'Authors', type: 'array', of: [{ type: 'string' }], readOnly: true },
    {
      name: 'attributionAuthors',
      title: 'Structured authors',
      type: 'array',
      of: [{ type: 'object', fields: attributionAuthorFields }],
      readOnly: true,
    },
    { name: 'journal', title: 'Journal', type: 'string', readOnly: true },
    { name: 'publishedAt', title: 'Publication date', type: 'datetime', readOnly: true },
    { name: 'year', title: 'Year', type: 'number', readOnly: true },
    { name: 'url', title: 'URL', type: 'url', readOnly: true },
    { name: 'discoverySources', title: 'Discovery sources', type: 'array', of: [{ type: 'string' }], readOnly: true },
    {
      name: 'evidence',
      title: 'Attribution evidence',
      type: 'object',
      readOnly: true,
      fields: [
        { name: 'isManuallyConfirmed', type: 'boolean', title: 'Manually confirmed' },
        { name: 'isManuallyRejected', type: 'boolean', title: 'Manually rejected' },
        { name: 'isPubmedConfirmed', type: 'boolean', title: 'PubMed confirmed' },
        { name: 'expectedOrcid', type: 'string', title: 'Expected ORCID' },
        { name: 'matchedOrcid', type: 'string', title: 'Matched ORCID' },
        { name: 'hasExactOrcid', type: 'boolean', title: 'Exact ORCID' },
        { name: 'hasConflictingOrcid', type: 'boolean', title: 'Conflicting ORCID' },
        { name: 'nameKind', type: 'string', title: 'Name form' },
        { name: 'matchedAuthor', type: 'string', title: 'Matched author' },
        { name: 'affiliationMatches', type: 'array', of: [{ type: 'string' }], title: 'Affiliation matches' },
        { name: 'recurringCoauthorCount', type: 'number', title: 'Recurring coauthor count' },
        { name: 'recurringCoauthors', type: 'array', of: [{ type: 'string' }], title: 'Recurring coauthors' },
        { name: 'queryPaths', type: 'array', of: [{ type: 'string' }], title: 'Query paths' },
      ],
    },
    { name: 'holdReason', title: 'Why review was required', type: 'text', readOnly: true },
    {
      name: 'snapshot',
      title: 'Normalized publication snapshot',
      type: 'object',
      fields: snapshotFields,
      readOnly: true,
      hidden: true,
    },
    {
      name: 'status',
      title: 'Status',
      type: 'string',
      options: {
        list: [
          { title: 'Pending', value: 'pending' },
          { title: 'Approved', value: 'approved' },
          { title: 'Rejected', value: 'rejected' },
        ],
      },
      validation: (Rule) => Rule.required(),
      readOnly: true,
    },
    { name: 'firstSeenAt', title: 'First seen', type: 'datetime', readOnly: true },
    { name: 'lastSeenAt', title: 'Last seen', type: 'datetime', readOnly: true },
    { name: 'lastNotifiedAt', title: 'Last notified', type: 'datetime', readOnly: true },
    { name: 'notificationCount', title: 'Notification count', type: 'number', readOnly: true },
    { name: 'reviewedAt', title: 'Reviewed at', type: 'datetime', readOnly: true },
    { name: 'reviewedBy', title: 'Reviewed by', type: 'string', readOnly: true },
  ],
  orderings: [
    {
      title: 'Pending first',
      name: 'pendingFirst',
      by: [
        { field: 'status', direction: 'asc' },
        { field: 'lastSeenAt', direction: 'desc' },
      ],
    },
  ],
  preview: {
    select: {
      title: 'title',
      researcher: 'researcherName',
      status: 'status',
    },
    prepare({ title, researcher, status }) {
      return {
        title: title || 'Publication attribution',
        subtitle: `${researcher || 'Unknown researcher'} • ${status || 'pending'}`,
      }
    },
  },
}

export default publicationAttributionReview
